export const USER_ASYNC_START = 'USER_ASYNC_START';
export const USER_ASYNC_FINISH = 'USER_ASYNC_FINISH';
export const USER_ASYNC_ERROR = 'USER_ASYNC_ERROR';

export const LISTEN_TO_USER_PROFILE = 'LISTEN_TO_USER_PROFILE';
