export const LISTEN_TO_CURRENT_PROFILE = 'LISTEN_TO_CURRENT_PROFILE';
export const LISTEN_TO_SELECTED_PROFILE = 'LISTEN_TO_SELECTED_PROFILE';
export const LISTEN_TO_USER_PHOTOS = 'LISTEN_TO_USER_PHOTOS';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
