export const USER_ASYNC_START = 'USER_ASYNC_START';
export const USER_ASYNC_FINISH = 'USER_ASYNC_FINISH';
export const USER_ASYNC_ERROR = 'USER_ASYNC_ERROR';

export const LISTEN_TO_CURRENT_PROFILE = 'LISTEN_TO_CURRENT_PROFILE';
export const LISTEN_TO_SELECTED_PROFILE = 'LISTEN_TO_SELECTED_PROFILE';
export const LISTEN_TO_USER_PHOTOS = 'LISTEN_TO_USER_PHOTOS';
