export const MEETUP_ASYNC_START = 'MEETUP_ASYNC_START';
export const MEETUP_ASYNC_FINISH = 'MEETUP_ASYNC_FINISH';
export const MEETUP_ASYNC_ERROR = 'MEETUP_ASYNC_ERROR';

export const MEETUP_LIST = 'MEETUP_LIST';
export const MEETUP_CREATE = 'MEETUP_CREATE';
export const MEETUP_UPDATE = 'MEETUP_UPDATE';
export const MEETUP_DELETE = 'DELETE_MEETUP';

export const LISTEN_TO_MEETUP_COMMENTS = 'LISTEN_TO_MEETUP_COMMENTS';
export const GET_MEETUP_COMMENTS_REQUEST = 'GET_MEETUP_COMMENTS_REQUEST';
export const GET_MEETUP_COMMENTS_SUCCESS = 'GET_MEETUP_COMMENTS_SUCCESS';
export const GET_MEETUP_COMMENTS_ERROR = 'GET_MEETUP_COMMENTS_ERROR';
