export const MEETUP_ASYNC_START = 'MEETUP_ASYNC_START';
export const MEETUP_ASYNC_FINISH = 'MEETUP_ASYNC_FINISH';
export const MEETUP_ASYNC_ERROR = 'MEETUP_ASYNC_ERROR';

export const MEETUP_LIST = 'MEETUP_LIST';
export const MEETUP_CREATE = 'MEETUP_CREATE';
export const MEETUP_UPDATE = 'MEETUP_UPDATE';
export const MEETUP_DELETE = 'DELETE_MEETUP';
